dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: lva-document-handler
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.7.6
- name: lva-eform-handler
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.3.1
- name: lva-eform-processor
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.1.4
- name: lva-electronic-page-handler
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.3.4
- name: lva-electronic-page-processor
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.2.3
- name: lva-image-processor
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.3.1
- name: lva-scanned-page-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.4.1
- name: lva-slip-generator
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.4.1
- name: lva-spreadsheet-generator
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.3.0
- name: lva-wingman-templates
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.3.5
